### Numpy Assignment

Write a function so that the columns of the output matrix are powers of the inputvector
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N -i -1.
HINT:  Such  a  matrix  with  a  geometric  progression  in  each  row  is  named  for  Alexandre-Theophile Vandermonde.

In [5]:
import numpy as np

In [10]:
x = np.array([1,2,3,4,5])
Y = 5
matrix1 = np.vander(x,Y,increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [11]:
np.linalg.det(matrix1)

287.9999999999977

Problem Statement:
Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows:
The moving average sequence has n-k+1 elements as shown below

Question: Write a function to find moving average in an array over a window:Test it over
[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [12]:
a = np.random.randint(10,size=10)
a

array([7, 4, 3, 7, 4, 1, 8, 3, 7, 6])

In [31]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    #print(ret[n])
    #print([n-1])
    #print(ret[n-1:]/n)
    return ret[n-1:]/n
    

In [32]:
moving_average(a)

array([4.66666667, 4.66666667, 4.66666667, 4.        , 4.33333333,
       4.        , 6.        , 5.33333333])